server:
  port: 7272

spring:
  datasource:
    url: jdbc:mysql://localhost:9696/AVM?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
    open-in-view: false